Convex-Dev/convex

- src/main/java/convex/cli/PeerStart.java
- src/main/java/convex/cli/peer/PeerManager.java
- src/main/java/convex/peer/Server.java
This is the second part of starting a peer with the other local peers.
This now gets the latest Signed Belief from one of the peers using `acquire` api call and then calls the `peer.mergeBeliefs` to merge the latest belief with the new peer.
The new peer seems to be one step behind until the next state is changed.
We have to do this, because when a peer starts up it only has the initial state, and so cannot process any transactions sent by the new peer keypair, to force a sync of data between peers.
> Cli peer sync

- src/main/java/convex/peer/Server.java
I realized that when hostname == null the `set-peer-data` also had no peerkey
> Fix set peer data call

- src/main/java/convex/cli/Helpers.java
- src/main/java/convex/cli/peer/PeerManager.java
- src/main/java/convex/net/Connection.java
- src/main/java/convex/net/Message.java
- src/main/java/convex/net/NIOServer.java
- src/main/java/convex/peer/API.java
- src/main/java/convex/peer/ConnectionManager.java
- src/main/java/convex/peer/Server.java
- src/test/java/convex/peer/MessageReceiverTest.java
1. On a peer close broadcast the GOODBYE message with a signed peer key
2. Process a GOODBYE message by a peer, if the peer is trusted then close the connection.
3. Set the trusted peer key in the `Connection class` to be `final`, can only be set on a new connection.
I want to stop the possibility of a bad actor just sending out random GOODBYE messages with a signed account key. In theory it is still possible, since the bad actor just needs to copy a previous message and send it out pretending to be the trusted peer.
Not sure how critical this is going to effect the security/stability of the network?
> Peer close

- src/main/java/convex/peer/Server.java
Fixes the `Server.joinNetwork`, not to connect straight away to all of the working peers.
Moved LEVEL_PARTIAL to FINER
> removed connecting to all peers on join

- src/main/java/convex/cli/peer/PeerManager.java
- src/main/java/convex/net/Connection.java
- src/main/java/convex/net/MessageReceiver.java
- src/main/java/convex/peer/ConnectionManager.java
- src/main/java/convex/peer/Server.java
- src/main/java/convex/peer/ServerInformation.java
I have fixed the refactoring to work with the cli.local.start
1. added back in the event messages for connection consensus change
2. After the initial connection via api to the peer to get the peer key, reconnect the server to the peer with the message handler assigned to the receive queue, to process messages
3. moved `processChallenge` to the ConnectionManager class
This does not solve an issue I'm having with another peer joining the local cluster. I will raise an issue for this..
> Fix cil local peers

- src/main/java/convex/core/data/prim/CVMChar.java
- src/main/java/convex/core/util/Utils.java
- src/test/java/convex/core/lang/CoreTest.java
- src/test/java/convex/util/UtilsTest.java
Stringifying a standalone CVMChar (eg. `(str \a)`) performs as before
(returns "a"), whereas stringifying CVMChars embedded in a container
(eg. `(str [\newline])`) produces a readable EDN representation (returns
"[\newline]").
Also fixes translating non-escaped chars to EDN. Previously, \a -> "a",
which is incorrect. Now, \a -> "\a".
> Fix #152, stringifying chars differently based on context

- convex-cli/src/test/java/convex/cli/output/OutputTest.java
- convex-core/src/main/java/convex/core/crypto/PEMTools.java
+ fixes importing python generated keys using encrypted PEM format.
now loads in the Bouncy Castle ciphers for decryption
+ cleanup test output
> Fix decrypt provider

- .github/workflows/tests.yml
- convex-core/src/main/java/convex/core/crypto/Ed25519KeyPair.java
- convex-core/src/test/java/convex/core/crypto/Ed25519Test.java
- convex-core/src/test/java/convex/core/crypto/PEMToolsTest.java
- convex-core/src/test/java/convex/core/crypto/SignKeyPairTest.java
This fixes the errors that have been occuring on the Ed25519KeyPair tests.
+ changed `assertEqual(kp1, kp2)` to `assertTrue(kp1.equals(kp2))`
+ moved the test action to test against java 15 instead of 11, since the private key conversion does not work in java11
So we may need to move up the minimum java requirement to java15 if we want to keep the Ed25519KeyPair equals on private key values
> Fix keypair tests

- convex-cli/src/main/java/convex/cli/Main.java
- convex-cli/src/main/java/convex/cli/PeerStart.java
when using config file, trailing spaces can be stored as parameter values. 
This removes leading and trailing spaces in parameter values
> add parameters strip of string values

- convex-cli/src/main/java/convex/cli/LocalStart.java
- convex-cli/src/main/java/convex/cli/Main.java
- convex-cli/src/main/java/convex/cli/peer/PeerManager.java
- convex-cli/src/test/java/convex/cli/CLIMainTest.java
- convex-gui/src/main/java/convex/gui/manager/mainpanels/PeersListPanel.java
- convex-peer/src/main/java/convex/peer/API.java
- convex-peer/src/test/java/convex/peer/ServerTest.java
allow the cli convex.local.start to be assigned a list of port numbers via the --ports option.
This allows for docker integration, so that the local network can be started with a set of predefined list of ports to expose/publish via docker.
> Cli port range

- convex
- convex-core/src/main/java/convex/core/crypto/Ed25519KeyPair.java
- convex-core/src/test/java/convex/core/crypto/PEMToolsTest.java
+ fixes the Ed25519KeyPair class equals method to work correctly for java11+
+ added absolute path for the java archive in the convex script file relative to the convex script path
> fix ed25519 equals for java11

- convex-peer/src/main/java/convex/api/Convex.java
- convex-peer/src/main/java/convex/peer/ConnectionManager.java
- convex-peer/src/main/java/convex/peer/Server.java
this is a fix for the missing data on status request. I have added a new method called `Convex.statusRequestSync`.
This does a async `statusRequest` and we get a missing data, then call the `acquire` to get the missing status message
> add status request sync with missing data fix

- convex-peer/src/main/java/convex/peer/ConnectionManager.java
I noticed that sometimes a peer does not get up to sync with the consensus, and then starts polling the belief. If the status hash is returned instead of the status data, then the `pollBelief` fails with a MissingData error. so to fix changed the `pollBelief` to call `requestStatusSync` which will acquire the missing data.
> change to use requestStatusSync

- convex-peer/src/main/java/convex/net/NIOServer.java
We obviously need to catch the 'CancelledKeyException' within the peer
server  connection loop.  When doing  so network  peers run  much more
stable on Linux hosts.
Signed-off-by: Otto Linnemann <linneman@gmx.de>
> catch missing exception in peer connection

- convex-core/src/main/cvx/convex/trust.cvx
Beyond the fact end users can use this function for validation,
such predicates also serve as informal documentation.
> Add trust monitor predicate in trust library

- convex-core/src/main/java/etch/Etch.java
Seems do to the trick, Java < 17 was complaining about `.duplicate` hence the value returned from `getInternalBuffer` must be cast.
Solves #394
> [394] Restore compatibility with Java < 17

- convex-cli/src/main/java/convex/cli/LocalStart.java
I tried running the `./convex local start` command for the first time but I kept getting a warning about insufficient key pairs, even though I definitely had enough in my keystore. I think the conditional is wrong here. After checking git blame I saw that the conditional used to check `count > keyPairList.size()` so I think it was just mistakenly flipped in [this commit](https://github.com/Convex-Dev/convex/commit/93e5c79032882a97e4dc325ce44b4a59565dfcb4). I'm happy to sign a contrib agreement BTW...I doubt this will be the only PR I submit ;)
> Fix incorrect 'insufficient key pairs' warning

- convex-core/src/main/java/convex/core/data/ABlob.java
- convex-core/src/main/java/convex/core/data/Hash.java
Fixes #427
I think I finally figured this one out, and unsurprisingly it's due to a stateful object (`MessageDigest`) being mutated at unexpected times. Specifically, in this method:
https://github.com/Convex-Dev/convex/blob/fbf52a1c5a336fafafb57eec6963c9e0a8af3005/convex-core/src/main/java/convex/core/data/ABlob.java#L163-L166
We're updating the digest, then calling `Hash.createFromDigest` which will return the hash and reset the digest object. This appears fine, but then we have this:
https://github.com/Convex-Dev/convex/blob/fbf52a1c5a336fafafb57eec6963c9e0a8af3005/convex-core/src/main/java/convex/core/data/Hash.java#L50-L53
Those static fields in `Hash` are calling `Hashing.sha3`, which is using the same `MessageDigest`. Static fields are initialized the first time a class is loaded, …
> Fix bad checksum error

- convex-core/src/main/java/convex/core/lang/RT.java
This overload of the `cons` method adds the args in a weird order that I am guessing is a typo: `y`, `x`, and `z`. It looks like it's supposed to add them back-to-front so they end up as `(x y z)` so I fixed it to do that. This method isn't used anywhere so maybe it should just be deleted?
> Fix cons overload

- convex-core/src/main/antlr4/convex/core/lang/reader/antlr/Convex.g4
- convex-core/src/test/java/convex/core/lang/ReaderTest.java
I noticed that `::foo` was being parsed as a symbol:
```
> (def ::foo "hello")
"hello"
> ::foo
"hello"
> (= 'foo '::foo)
true
```
It'll be a breaking change to fix this later, so it probably should be fixed now. I just adjusted up the antlr file so it parses as a keyword.
This leads me to a few questions:
1. Should this throw an exception (maybe during validation in `Keyword.java`) so this syntax can be used later for namespaced keywords? I think probably so.
2. While we're talking about keywords, should `(keyword "hello world")` throw? It currently returns `:hello world`, just like clojure does, but it will of course fail to read as a keyword later. I wouldn't copy this particular quirk from clojure...
> Parse ::foo as a keyword, not a symbol

- convex-peer/src/main/java/convex/net/Connection.java
Initializing IO resources dynamically is friendlier towards native compilation. In some cases, it is pretty much mandatory.
Note: odd, I know I hit this problem about a year ago and was fairly sure we had a fix. This seems to be the right place to move `selector` initialization?
> Initialize `Connection.selector` dynamically

- convex-core/src/main/java/etch/Etch.java
- convex-core/src/test/java/etch/api/TestEtch.java
As a way of retrieving the "real" Etch size.
> Add `Etch.getDataLength` method

- convex-core/src/main/java/convex/core/data/ARecord.java
- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-core/src/main/java/convex/core/data/SignedData.java
While `SignedData` is not a CVM value, there is an incentive for making it easier to handle in tools like the Convex Shell.
> Turn SignedData into a Record

- convex-core/src/main/java/convex/core/crypto/ASignature.java
- convex-core/src/main/java/convex/core/crypto/Ed25519Signature.java
- convex-core/src/main/java/convex/core/data/AArrayBlob.java
- convex-core/src/main/java/convex/core/data/ABlob.java
Signatures are conceptually similar to blobs, akin to hashes. Making that relationship explicit makes signatures more convenient to handle in environments such as the Convex Shell.
Note: This one might be more controversial but it should complete my quest of making main user exposed types convenient to use similarly proper "on-chain" types. I've added support for running peers in the Shell (the last missing part) and I don't see any other remaining type to support in that way.
> Make `ASignature` a subclass of `AArrayBlob`

- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-core/src/main/java/convex/core/transactions/ATransaction.java
- convex-core/src/main/java/convex/core/transactions/Call.java
- convex-core/src/main/java/convex/core/transactions/Invoke.java
- convex-core/src/main/java/convex/core/transactions/Transfer.java
Mainly about making `ATransaction` an `ARecord` as mentioned previously, so that transactions print full information and are more convenient to handle.
I also took the opportunity to slightly improve naming.
> Turn transaction types into records 

- convex-core/src/main/java/convex/core/lang/Context.java
- convex-core/src/test/java/convex/core/lang/CoreTest.java
`Context` would fail with a class cast exception since it was not validating that the given URL was indeed a string.
> Fix `set-peer-data` failing on non-string URLs

- convex-core/src/main/java/convex/core/Order.java
- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-core/src/test/java/convex/core/data/RecordTest.java
Note: Probably the last "recordification", making it more consistent with `Belief`, `Block`, etc, which are already records
> Make `Order` a subclass of `ARecord`

- convex-core/src/main/java/convex/core/Peer.java
- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-peer/src/main/java/convex/peer/Server.java
See commit descriptions for details.
I think we have been overthinking #346 . All that's really needed is allowing the user to provide an optional key if peer data cannot be stored directly at the root.
> Allow persisting peer data under a key

- convex-peer/src/main/java/convex/peer/Server.java
The reported value was the number of keys in the ordering (as a record) instead of the number of blocks.
> Fix ordering length reported in peer status

- convex-core/src/main/cvx/convex/lab/cns.cvx
- convex-core/src/test/cvx/test/convex/lab/cns.cvx
The new Convex Name Service actor now understand hierarchical paths.
Note that it must be initiated using its self-destructing `init`
function.
When approved, it will entirely remplace `*registry*`.
This commit also contains a full test suite for the Convex Runner.
> Add CVX code for an improved CNS

- convex-cli/src/docs/asciidoc/index.adoc
The documentation uses two different local ports as an example: 8088 and 80888 ([see link](https://convex-dev.github.io/convex/convex-cli/#_starting_the_peer_with_convex_world)). I'm assuming this is a typo. Although this could well be the case if the local process is proxied by another process, I think in standard setups this port would be equal in both cases.
> Correct port number in example

- convex
This rolls back `./convex` to a previous version with correct line endings. 
The current version gives:
```
./convex
zsh: ./convex: bad interpreter: /bin/bash^M^MBASE_PATH=$(dirname $0)^MJAR_NAME=`ls -1 $BASE_PATH/convex-cli/target/convex-cli.jar`^M^M# echo "using: $JAR_NAME"^M^Mja: no such file or directory
```
> Rollback ./convex to previous version

- convex-core/src/main/java/convex/core/text/Text.java
The unit tests fails when executed on a system configured with a comma as the decimal separator rather than a dot, due to locale-specific formatting discrepancies.
This PR fixes the issue and the unit tests succeed.
> Make the decimal formatters culture invariant
