- README.md
- convex
- convex.bat
- pom.xml
- src/main/java/convex/cli/AccountCreate.java
- src/main/java/convex/cli/KeyGenerate.java
- src/main/java/convex/cli/Main.java
- src/main/java/convex/cli/peer/PeerManager.java
- src/main/java/convex/core/util/Utils.java
- src/main/java/convex/peer/ConnectionManager.java
+ renamed java file from target/convex.jar to target/convex-jar-with-dependencies.jar
+ cleanup peer response
+ allowed CLI command .create.account to also create key as default with no public-key or key-index
> Fix cli local

- src/test/java/convex/api/ConvexTest.java
now can run tests on convex-test
> add wait for convex api object

- src/main/java/convex/api/Convex.java
- src/main/java/convex/cli/AccountCreate.java
- src/main/java/convex/cli/Constants.java
- src/main/java/convex/cli/KeyGenerate.java
- src/main/java/convex/cli/LocalStart.java
- src/main/java/convex/cli/Main.java
- src/main/java/convex/cli/peer/PeerManager.java
- src/test/java/convex/api/ConvexTest.java
- src/test/java/convex/peer/ServerTest.java
+ Fix cli convex.local.start to create own keys for new network
+ inc sequence in ConvexTest, to get `createAccount` working
> Fix cli local start

- convex-cli/src/main/java/convex/cli/Main.java
- convex-cli/src/main/java/convex/cli/PeerStart.java
- convex-cli/src/main/java/convex/cli/peer/PeerManager.java
- convex-peer/src/main/java/convex/peer/Server.java
added `aquireState` method to get the same base network state for the joining peer
So the joining peer has the same network Id
> Add peer state

- convex-cli/src/test/java/convex/cli/output/OutputTest.java
> CLI output tests

- convex-cli/src/test/java/convex/cli/peer/SessionTest.java
> Cil test session

- convex-cli/pom.xml
- convex-cli/src/main/java/convex/cli/Key.java
- convex-cli/src/main/java/convex/cli/KeyExport.java
- convex-cli/src/main/java/convex/cli/KeyImport.java
- convex-cli/src/main/java/convex/cli/Main.java
- convex-cli/src/test/java/convex/cli/CLICommandKeyExportTest.java
- convex-cli/src/test/java/convex/cli/CLICommandKeyImportTest.java
- convex-core/src/main/java/convex/core/crypto/Ed25519KeyPair.java
- convex-core/src/main/java/convex/core/crypto/PEMTools.java
- convex-core/src/test/java/convex/core/crypto/Ed25519Test.java
- convex-core/src/test/java/convex/core/crypto/PEMToolsTest.java
+ exclude sl4j-simple from convex-gui
+ add encrypt/decrypt in PEM tools
+ fixed Ed25519KeyPair equals to compare private key correctly
+ added convex.key import/export  in CLI
> Keystore import export

- convex-cli/src/main/java/convex/cli/Main.java
- convex-cli/src/main/java/convex/cli/PeerStart.java
+ add --peer option to cli.convex.peer.start - to provide a remote hostname & port to connect to a remote peer
+ fixed find key in keystore bug
> add peer option, fix keystore find bug

- .gitignore
- convex-core/src/main/java/convex/core/data/AccountStatus.java
- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-core/src/main/java/convex/core/lang/Context.java
- convex-core/src/main/java/convex/core/lang/Core.java
- convex-core/src/main/java/convex/core/lang/Symbols.java
- convex-core/src/main/resources/lang/core.cvx
- convex-core/src/test/java/convex/core/lang/CoreTest.java
Resolves #259.
It seems there are only a couple of tests failing in the GUI because I removed `getExports` from `AccountStatus`. Could you have a quick look since I've never touched the GUI and I have lots of other stuff to finish?
Latter step will be to remove `export` and rename `exports?` to `callable?`, will imply syncing the CVX libraries.
> New export

- convex-core/src/main/java/convex/core/lang/Context.java
- convex-core/src/main/java/convex/core/lang/Symbols.java
- convex-core/src/main/resources/lang/core-metadata.doc
PS: some network tests fail, as in the previous commit, but all the `convex-core` tests pass.
> Fix #245, remove `*aliases*`

- convex-peer/src/main/java/convex/peer/Server.java
Currently this line fails if no EVENT-HOOK is set, change to use the default of null
> add default null for no event-hook

- convex-core/src/main/java/convex/core/lang/ops/Lookup.java
- convex-core/src/test/java/convex/core/lang/CoreTest.java
So you can try it for yourself. I tend to prefer it that way since accuracy > convenience.
> Print lookups accurately (fix #277)

- convex-cli/src/main/java/convex/cli/PeerStart.java
- convex-cli/src/main/java/convex/cli/peer/PeerManager.java
- convex-core/src/main/java/convex/core/Constants.java
- convex-peer/src/main/java/convex/peer/Server.java
- convex-peer/src/test/java/convex/peer/ServerTest.java
use SOURCE configuration to launch a server
Add a delay after create peer for the test network to write the new consensus,
then try and launching a new peer
> Launch peer changes

- convex-cli/src/test/java/convex/cli/CLICommandKeyExportTest.java
- convex-cli/src/test/java/convex/cli/CommandLineTester.java
Better tests on public key exporting
> test for export a public key

- convex-peer/src/main/java/convex/peer/API.java
- convex-peer/src/test/java/convex/api/ConvexTest.java
- convex-peer/src/test/java/convex/peer/ServerTest.java
- convex-peer/src/test/java/convex/peer/TestNetwork.java
To try to improve testing, I have moved the ServerTest startup to a new test class NetworkTest
The class NetworkTest checks that all servers are in sync before returning an instance
> add new TestNetwork class to provide a test local network

- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-peer/src/main/java/convex/peer/ConnectionManager.java
- convex-peer/src/main/java/convex/peer/Server.java
Poll delay can now be provided in the server config map or otherwise default value is used.
> Parameterize server poll delay

- README.md
- convex-cli/src/main/java/convex/cli/peer/PeerManager.java
- convex-core/src/main/java/convex/core/data/Keywords.java
- convex-core/src/main/java/convex/core/util/Utils.java
- convex-peer/src/main/java/convex/net/NIOServer.java
- convex-peer/src/main/java/convex/peer/API.java
- convex-peer/src/main/java/convex/peer/Server.java
+ renamed HOST keyword to BIND_ADDRESS
+ default BIND_ADDRESS to localhost
+ If a non local URL is set, then default BIND_ADDRESS to 0.0.0.0
+ setHostname for the genesis server on local startup
+ set correct docs link in README.md
> Release 0.7.0

- convex-cli/src/docs/asciidoc/index.adoc
- convex-cli/src/main/java/convex/cli/PeerStart.java
- convex-cli/src/main/java/convex/cli/Status.java
- convex-cli/src/main/java/convex/cli/peer/PeerManager.java
- convex-peer/src/main/java/convex/api/Convex.java
+ removed `acquireHash` from requestStatusSync
+ add more docs
+ add --url and --bindAddress to `convex.peer.start` command
> Release 0.7.0 updates

- convex-cli/src/docs/asciidoc/index.adoc
> CLI doc updated

- convex-core/src/main/java/etch/Etch.java
- convex-core/src/main/java/etch/EtchStore.java
no code change, but just remove all trailing tabs from the source files in etch
> remove trailing tabs

- convex-core/src/main/java/etch/Etch.java
- convex-core/src/test/java/etch/api/TestEtch.java
Changed the following:
+ new `setDataLength` method to assign and check the new value
+ added a large data test, that will fail on the old code
+ correctly set the dataLength for large db stores
> Fix data length calculation

- convex-core/src/test/java/convex/test/generators/PrimitiveGen.java
> Improve coverage of property tests by including verious sizes of blob types.

- convex-cli/src/main/java/convex/cli/Main.java
Fix key index to correctly return the actual index of the key
> fix key index bug

- convex-core/src/main/java/convex/core/lang/Context.java
aloowance -> allowance, see screenshot below from Sandbox
> fix: typo in error message

- convex-core/src/main/cvx/convex/core/metadata.cvx
<div>Changed `set-2u to `set-2`</div>
> Corrected a typo

- convex-core/pom.xml
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/world/convex/README.md
> work-around non-reproducible ANTLR output

- .github/workflows/tests.yml
- README.md
- convex-cli/pom.xml
Testing Java 11 and 17 across all major OSes.
Note: I changed the target version of the CLI to 11. Why was it set to 17? Tests pass but please make sure it is alright.
> Run CI tests over a matrix

- convex-cli/pom.xml
- pom.xml
> upgrade log versions

- convex-core/src/main/java/etch/Etch.java
- convex-core/src/main/java/etch/EtchStore.java
- convex-peer/src/main/java/convex/peer/Server.java
Fixes some typos in Server logging + make Etch report its filename in canonical form
> Fix server logging typos

- README.md
- docs/coding-principles.md
> Fix: typos

- LICENSE.md
> docs: update LICENSE.md

- convex
Updated the UNIX shell script to point at the convex-integation JAR.
> Updated the UNIX shell script to point at the convex-integation JAR.

- convex-gui/src/main/java/convex/gui/keys/KeyGenPanel.java
Fixed typo in the word mnemonic - 2 occurrences. (Possibly the smallest change request ever!)
> Fixed typo in the word mnemonic - 2 occurrences.
